name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  activity: ^1.5.3+5
  another_flushbar: ^1.12.30
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  go_router: ^11.1.3
  injectable: ^2.3.0
  jovial_svg: ^1.1.20
  luthor: ^0.1.6
  quickeydb: ^1.2.0+8

dev_dependencies:
  build_runner: ^2.4.6
  device_preview: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator: ^2.4.0

  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/si/
    - assets/images/

  fonts:
    - family: Gogh
      fonts:
        - asset: assets/fonts/goghregular.ttf
          weight: 400
        - asset: assets/fonts/goghmedium.ttf
          weight: 500
        - asset: assets/fonts/goghbold.ttf
          weight: 700
        - asset: assets/fonts/goghblack.ttf
          weight: 900

